services:
  api-php:
    build:
      context: .
      dockerfile: docker/api-php/Dockerfile
      args:
        USERID: 1000
    volumes:
      - ./api:/var/www/html
    networks:
      - default
    expose:
      - 9000
    depends_on:
      - db
    environment:
      APP_ENV: 'dev'
      APP_SECRET: '0f4e9fce56a0fac70f6391e974def300'
      DATABASE_URL: "mysql://root:toor@db:3306/cgenerator?serverVersion=8&charset=utf8mb4"
      MESSENGER_TRANSPORT_DSN: 'amqp://cgenerator:cgenerator@rabbit:5672/%2f/code_generator_queue'

  worker-php:
    build:
      context: .
      dockerfile: docker/worker-php/Dockerfile
      args:
        USERID: 1000
    volumes:
      - ./worker:/var/www/html
    networks:
      - default
    depends_on:
      - rabbit
      - api-php
    environment:
      APP_ENV: 'dev'
      APP_SECRET: '0f4e9fce56a0fac70f6391e974def300'
      MESSENGER_TRANSPORT_DSN: 'amqp://cgenerator:cgenerator@rabbit:5672/%2f/code_generator_queue'

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
      args:
        USERID: 1001
    volumes:
      - ./client:/var/www
    ports:
      - 8080:8080
    networks:
      - default

  nginx:
    image: nginx:1.23.2
    ports:
      - 80:80
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
    depends_on:
      - api-php

  db:
    image: mariadb:10.9.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: cgenerator
      MYSQL_PASSWORD: cgenerator
      MYSQL_DATABASE: cgenerator
    networks:
      - default

  rabbit:
    image: rabbitmq:3.13.1-management
    expose:
      - 15672
    volumes:
      - ./docker/rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbit/definitions.json:/etc/rabbitmq/definitions.json:ro
    environment:
      RABBITMQ_DEFAULT_USER: 'cgenerator'
      RABBITMQ_DEFAULT_PASS: 'cgenerator'
    networks:
      - default
    ports:
      - 15672:15672

networks:
  default:
    driver: bridge
